# Generated by Django 4.2.3 on 2023-07-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAnnotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower',
            name='reports_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middles', to='DjangoAnnotation.middle'),
        ),
        migrations.AlterField(
            model_name='middle',
            name='reports_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middles', to='DjangoAnnotation.top'),
        ),
    ]
