# Generated by Django 4.2.3 on 2023-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAnnotation', '0003_alter_lower_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='middle',
            name='klass',
            field=models.IntegerField(default=1),
        ),
    ]
