# Generated by Django 4.2.3 on 2023-07-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAnnotation', '0004_middle_klass'),
    ]

    operations = [
        migrations.AddField(
            model_name='lower',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
